---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

availabilityZones:
  - us-east-1a
  - us-east-1d

metadata:
  name: eks-boilerplate
  version: "1.20"
  region: us-east-1
  tags:
    app: "eks-boilerplate"
    env: "dev"
    type: "eks-cluster"

managedNodeGroups:
  - name: nodegroup-1
    desiredCapacity: 2
    instanceType: t3.medium
    ssh:
      enableSsm: true