---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readonlyrole
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developerrole
rules:
  - apiGroups: ["*"]
    resources: ["services","deployments", "pods", "configmaps", "pods/log"]
    verbs: ["get", "list", "watch", "update", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adminrole
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]