# https://gist.github.com/randomk/9e8a1145820428f201ab277caf397790
config:
  configFile: |-
    email_domains = [ "*" ]
    upstreams = [ "file:///dev/null" ]

# https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview
extraArgs:
  provider: oidc
  provider-display-name: "Cognito SSO"
  cookie-secure: false
  cookie-name: "_oauth2_proxy"
  skip-provider-button: true
  scope: openid

ingress:
  enabled: true
  path: /oauth2
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    kubernetes.io/ingress.class: "nginx"
  ingressClassName: nginx
