apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readonlyrole
rules:
  - apiGroups: [""]
    resources: ["services","deployments", "pods", "pods/log"]
    verbs: ["get", "list", "watch"]