AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS for Postgres"

Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.

Mappings:
  Variables:
    prod:

    dev:
      dbInstance: db.t2.micro
      storageSize: "5"
      backupRetentionPeriod: 0
      PrivateSubnet1: ""
      PrivateSubnet2: ""
      VpcId: ""
      EcsSecurityGroup: ""
      BastionSecurityGroup: ""

Conditions:
  isProduction: !Equals [ !Ref Env, prod ]

Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      DBInstanceIdentifier: !Sub ${App}-${Env}-rds
      DBName: !Ref App
      Engine: postgres
      StorageEncrypted: !If [ isProduction, true, false ]
      BackupRetentionPeriod: !FindInMap [ Variables, !Ref Env, backupRetentionPeriod ]
      PreferredBackupWindow: "9:00-10:00"
      PreferredMaintenanceWindow: "mon:10:00-mon:11:00"
      MasterUsername: !Join [ '', [ '{{resolve:secretsmanager:', !Ref Secret, ':SecretString:username}}' ] ]
      MasterUserPassword: !Join [ '', [ '{{resolve:secretsmanager:', !Ref Secret, ':SecretString:password}}' ] ]
      DBInstanceClass: !FindInMap [ Variables, !Ref Env, dbInstance ]
      VPCSecurityGroups:
        - !GetAtt DatabaseSecurityGroup.GroupId
      AllocatedStorage: !FindInMap [ Variables, !Ref Env, storageSize ]
      StorageType: gp2
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBParameterGroupName: !Ref DBParameterGroup
      MonitoringInterval: !If [ isProduction, 60, 0 ]
      MonitoringRoleArn: !If [ isProduction, !GetAtt MonitoringRole.Arn, !Ref AWS::NoValue ]
      EnablePerformanceInsights: true
      EnableIAMDatabaseAuthentication: true
      EnableCloudwatchLogsExports:
        - postgresql
        - upgrade
      Tags:
        - Key: app
          Value: !Ref App
        - Key: env
          Value: !Ref Env
        - Key: type
          Value: storage

  MonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - monitoring.rds.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: RDS for postgres custom default
      Family: postgres12
      Parameters:
        rds.force_ssl: !If [ isProduction, 1, 0 ]
      Tags:
        - Key: app
          Value: !Ref App
        - Key: env
          Value: !Ref Env
        - Key: type
          Value: storage

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: db subnets
      SubnetIds:
        - !FindInMap [ Variables, !Ref Env, PrivateSubnet1 ]
        - !FindInMap [ Variables, !Ref Env, PrivateSubnet2 ]
      Tags:
        - Key: app
          Value: !Ref App
        - Key: env
          Value: !Ref Env
        - Key: type
          Value: network

  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'RDS Postgres Database secret'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "rebugitsu"}'
        GenerateStringKey: 'password'
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: app
          Value: !Ref App
        - Key: env
          Value: !Ref Env
        - Key: type
          Value: security

  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref Secret
      TargetId: !Ref DBInstance
      TargetType: AWS::RDS::DBInstance

  #This resource policy denies the DeleteSecret action to all principals within the current account
  SecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref Secret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: secretsmanager:DeleteSecret
            Resource: "*"

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Fargate traffic to RDS
      VpcId: !FindInMap [ Variables, !Ref Env, VpcId ]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !FindInMap [ Variables, !Ref Env, EcsSecurityGroup ]
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !FindInMap [ Variables, !Ref Env, BastionSecurityGroup ]
      SecurityGroupEgress:
        - IpProtocol: "-1"
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: app
          Value: !Ref App
        - Key: env
          Value: !Ref Env
        - Key: type
          Value: network


  #ALARMS ===================================================
  DBAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Stack Alarm Topic
      Tags:
        - Key: app
          Value: !Ref App
        - Key: env
          Value: !Ref Env
        - Key: type
          Value: event

  CPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Database CPU utilization is over 80%.
      Namespace: AWS/RDS
      MetricName: CPUUtilization
      Unit: Percent
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstance
      AlarmActions:
        - Ref: DBAlarmTopic
      InsufficientDataActions:
        - Ref: DBAlarmTopic

  FreeStorageAlarm:
    Condition: isProduction
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: 'RDS Free Storage Alarm'
      ComparisonOperator: LessThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstance
      EvaluationPeriods: 1
      MetricName: FreeStorageSpace
      Namespace: AWS/RDS
      Period: 60
      Statistic: Average
      Threshold: 2147483648
      TreatMissingData: ignore
      Unit: Bytes
      AlarmActions:
        - Ref: DBAlarmTopic
      InsufficientDataActions:
        - Ref: DBAlarmTopic

#OUTPUTS ==================================================
Outputs:
  # POSTGRES_HOST
  PostgresHost:
    Description: "RDS host endpoint"
    Value: !GetAtt DBInstance.Endpoint.Address

  # POSTGRES_PORT
  PostgresPort:
    Description: "RDS host port"
    Value: !GetAtt DBInstance.Endpoint.Port

  # POSTGRES_CREDENTIALS_ARN
  PostgresCredentialsArn:
    Description: "RDS Secret manager arn"
    Value: !Ref Secret
